In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [11]:
np.concatenate([arr1, arr1], axis = 0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
ser1 = Series([0, 1, 2], index = ["T", "U", "V"])
ser2 = Series([3, 4], index = ["X", "Y"])
ser1

T    0
U    1
V    2
dtype: int64

In [17]:
ser2

X    3
Y    4
dtype: int64

In [21]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [23]:
pd.concat([ser1, ser2], axis = 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [25]:
pd.concat([ser1, ser2], axis = 0)

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [29]:
# adding index hierarchy
pd.concat([ser1, ser2], keys = ["cat1", "cat2"])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [31]:
dframe1 = DataFrame(np.random.randn(4, 3), columns = ["X", "Y", "Z"])
dframe2 = DataFrame(np.random.randn(3, 3), columns = ["Y", "Q", "X"])
dframe1

X         Y         Z
0  1.370956  0.132348 -1.446034
1  1.033724 -0.534076 -0.458740
2 -1.215459 -0.189351 -0.703524
3  0.950618 -2.185325  0.335734

In [33]:
dframe2

Y         Q         X
0 -0.878060 -1.366783 -1.078204
1 -1.612126 -1.179239 -0.235407
2  0.594454 -0.329222 -0.725034

In [35]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0  1.370956  0.132348 -1.446034       NaN
1  1.033724 -0.534076 -0.458740       NaN
2 -1.215459 -0.189351 -0.703524       NaN
3  0.950618 -2.185325  0.335734       NaN
0 -1.078204 -0.878060       NaN -1.366783
1 -0.235407 -1.612126       NaN -1.179239
2 -0.725034  0.594454       NaN -0.329222

In [37]:
pd.concat([dframe1, dframe2], ignore_index = True)

X         Y         Z         Q
0  1.370956  0.132348 -1.446034       NaN
1  1.033724 -0.534076 -0.458740       NaN
2 -1.215459 -0.189351 -0.703524       NaN
3  0.950618 -2.185325  0.335734       NaN
4 -1.078204 -0.878060       NaN -1.366783
5 -0.235407 -1.612126       NaN -1.179239
6 -0.725034  0.594454       NaN -0.329222

In [39]:
# pandas concat --- https://pandas.pydata.org/docs/reference/api/pandas.concat.html
# numpy concatenate --- https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html