In [3]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
# randomly reordering data

In [7]:
dframe = DataFrame(np.arange(16).reshape(4, 4))

In [9]:
# random assortment of 4 numbers
blender = np.random.permutation(4)

In [11]:
blender

array([3, 0, 2, 1])

In [13]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [17]:
# reorder by blender --- 3 is 1st, 0 is second, etc.
dframe.take(blender)

0   1   2   3
3  12  13  14  15
0   0   1   2   3
2   8   9  10  11
1   4   5   6   7

In [19]:
box = np.array([1, 2, 3])

In [23]:
shaker = np.random.randint(0, len(box), size = 10)

In [25]:
shaker

array([1, 2, 1, 1, 2, 2, 1, 2, 2, 0])

In [27]:
hand_grabs = box.take(shaker)
hand_grabs

array([2, 3, 2, 2, 3, 3, 2, 3, 3, 1])