In [1]:
import numpy as np

In [5]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [7]:
np.save('myArray', arr)

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.load('myArray.npy')

array([0, 1, 2, 3, 4])

In [17]:
arr1 = np.load('myArray.npy')
arr1

array([0, 1, 2, 3, 4])

In [19]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.savez('zipArray.npz', x = arr1, y = arr2)

In [27]:
archive_array = np.load('zipArray.npz')

In [31]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [35]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# save and load text
np.savetxt('whatever.txt', array_to_save, delimiter = ',')
arr = np.loadtxt('whatever.txt', delimiter = ',')