In [1]:
import numpy as np

In [3]:
my_list1 = [1, 2, 3, 4]

In [5]:
my_array1 = np.array(my_list1)

In [7]:
my_array1

array([1, 2, 3, 4])

In [9]:
my_list2 = [11, 22, 33, 44]

In [11]:
my_lists = [my_list1, my_list2]

In [13]:
my_lists

[[1, 2, 3, 4], [11, 22, 33, 44]]

In [15]:
my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [17]:
my_array2.shape

(2, 4)

In [21]:
my_array2.dtype

dtype('int32')

In [23]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [25]:
my_zeros_array = np.zeros(5)
my_zeros_array

array([0., 0., 0., 0., 0.])

In [27]:
my_zeros_array.dtype

dtype('float64')

In [31]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.empty(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [37]:
np.arange(5, 25, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23])